Updated

diff --git a/bin/dodigit b/bin/dodigit
--- a/bin/dodigit
+++ b/bin/dodigit
@@ -1,4 +1,5 @@
 #!/bin/csh -fb
+set job_id = "20161226-234150-735c"
 set class = "$1"
 set files = "$1-files.txt"
 set scores = "$1-scores.json"
@@ -11,7 +12,6 @@ if (! -s "$files") then
 endif
 if (! -s "$scores" || ((-M "$files") > (-M "$scores"))) then
     set surl = "http://169.50.131.114:5001//models/images/classification/classify_many.json"
-    set job_id = "20161226-234150-735c"
 
     set lc = `wc -l "$files" | awk '{ print $1 }'`
     echo `date` "$0 $$ -- creating $scores ($lc) using $job_id" >& /dev/stderr
@@ -19,6 +19,7 @@ if (! -s "$scores" || ((-M "$files") > (-M "$scores"))) then
     @ a = 1
     @ b = 0
     @ z = 100
+    unset started
     while ($a <= $lc)
 	@ b += $z
 	if ($b > $lc) set b = $lc
@@ -31,11 +32,17 @@ if (! -s "$scores" || ((-M "$files") > (-M "$scores"))) then
 	curl -s -q -L -X POST -F "image_list=@$t" -F "job_id=$job_id" "$surl" >! "$s"
 	rm -f "$t"
 	if (-s "$s") then
-	    set err = `jq '.error.message' "$s"`
+	    set err = `/usr/local/bin/jq '.error.message' "$s"`
 	    if ("$err" != "null") then
 		echo `date` "$0 $$ -- ERROR: $err" >& /dev/stderr
 	    else
-		cat "$s" >>! "$scores"
+	        if ($?started) then
+		    echo "," >> "$scores"
+		else
+		    echo "[" >>! "$scores"
+		    set started = true
+		endif
+		cat "$s" >> "$scores"
 	    endif
 	else
 	    echo `date` "$0 $$ -- NO RESULTS" >& /dev/stderr
@@ -43,22 +50,35 @@ if (! -s "$scores" || ((-M "$files") > (-M "$scores"))) then
 	@ a = $b + 1
 	rm -f "$s"
     end
+    echo "]" >> "$scores"
 endif
 if (-s "$files" && -s "$scores" && ((! -s "$results") || ((-M "$scores") > (-M "$results")))) then
     echo `date` "$0 $$ -- ITERATING over $files and $scores" >& /dev/stderr
+    unset started
     foreach i ( `cat "$files"` )
 	set j = `echo "$i" | sed "s/.*db=\(.*\)&class=\(.*\)&id=\(.*\)/\1\/\2\/\3/"`
 	set noglob
-	set q = `jq -r '.classifications."'"$i"'"' "$scores"`
+	set q = `/usr/local/bin/jq '[.[]|.classifications."'"$i"'"[]?]' "$scores"`
 	if ($#q > 1) then
 	    # get first class (TOP1)
-	    set h = `jq -r '.classifications."'"$i"'"[0][0]' "$scores" | sed "s/.*class=\(.*\)/\1/"`
+	    set h = `echo "$q" | /usr/local/bin/jq -r '.[0][0]' | sed "s/.*class=\(.*\)/\1/"`
 	    # get all scores (TOP5 is default)
-	    set k = `jq -r '.classifications."'"$i"'"[][1]' "$scores" | /usr/local/bin/gawk 'BEGIN { mx=0; mn=100; nz=0;c=0; s = 0;v=0 } { c++; if ($1 > mx) mx=$1; if ($1 < mn) mn=$1; if($1 > 0) { nz++; s += $1; m = s/nz; vs += ($1 - m)^2; v=vs/nz} } END { sd = sqrt(v); k = (mx - m)/sd; printf "\"count\":%d,\"non-zero\":%d,\"min\":%f,\"max\":%f,\"sum\":%f,\"mean\":%f,\"stdev\":%f,\"nsd\":%f", c, nz, mn, mx, s, m, sd, k }'`
+	    set k = `echo "$q" | /usr/local/bin/jq -r '.[][1]' | awk 'BEGIN { mx=0; mn=100; nz=0;c=0; s = 0;v=0 } { c++; if ($1 > mx) mx=$1; if ($1 < mn) mn=$1; if($1 > 0) { nz++; s += $1; m = s/nz; vs += ($1 - m)^2; v=vs/nz} } END { sd = sqrt(v); k = (mx - m)/sd; printf "\"count\":%d,\"non-zero\":%d,\"min\":%f,\"max\":%f,\"sum\":%f,\"mean\":%f,\"stdev\":%f,\"nsd\":%f", c, nz, mn, mx, s, m, sd, k }'`
 	    unset noglob
-	    echo '{"image":"'"$j"'","top1":"'"$h"'",'"$k"'}'
+	    if ($?started) then
+	        echo "," >> "$results"
+	    else
+	        echo '{"job":"'"$job_id"'","results":[" >! "$results"
+		set started = true
+	    endif
+	    echo '{"image":"'"$j"'","top1":"'"$h"'",'"$k"'}' >> "$results"
 	else
 	    echo `date` "$0 $$ -- NO RESULT: $i" >& /dev/stderr
         endif
     end
+    echo "]}" >> "$results"
+endif
+if (-s "$results") then
+    echo `date` "$0 $$ -- LOWEST RANK: " `jq '.|sort_by(.max)|sort_by(.nsd)' kitchen-results.json | jq '.[1]' "$results"`
+    echo `date` "$0 $$ -- HIGHEST RANK: " `jq '.|sort_by(.max)|sort_by(.nsd)' kitchen-results.json | jq '.[-1]' "$results"`
 endif
